
name: Deploy Next.js application

on:
  push:
    branches:
      - main
jobs:
  minikube-job:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: '1.34.0'
          driver: 'docker'
          container-runtime: 'containerd'
          kubernetes-version: 'v1.32.0'
          cpus: '2'
          memory: '4000m'
          addons: 'ingress,dashboard'

      - name: Verify cluster
        run: kubectl get nodes


      - name: Deploy YAML to Minikube
        run: kubectl apply -f k8s/deployment.yaml

